// Generated by typings
// Source: typings/custom/SoyTemplates.d.ts
declare const Com: {
    Softwire: {
        Jira: {
            Example: {
                Templates: {
                    Main: (params: {
                        name: string,
                        message: string
                    }) => string,
                    Error: (params: {
                        title: string,
                        content: string
                    }) => string,
                    Configuration: (params: {
                        prefix: string,
                        validation: ExampleConfigValidation,
                        preferences: {
                            name: string,
                            refresh: any // TODO
                            isConfigured: boolean
                        }
                    }) => string,
                }
            }
        }
    }
};

declare interface ExampleConfigValidation {
    maxNameLength: number
}
